/*
 * generated by Xtext 2.25.0
 */
package com.hcl.products.onetest.lang.script.parser.antlr;

import com.hcl.products.onetest.lang.script.parser.antlr.internal.InternalScriptParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class ScriptTokenSource extends AbstractIndentationTokenSource {

	public ScriptTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		return token.getType() == InternalScriptParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		return InternalScriptParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		return InternalScriptParser.RULE_END;
	}

}
